---
openapi: 3.0.1
info:
  title: Consent Management API
  description: Consent Management application API
  version: '1.0'
paths:
  "/consents/{consentId}/authorization-resource/{authorizationId}":
    get:
      tags:
        - Authorization Resource
      summary: Retrieve Consent Authorization Resource
      description: Retrieve a specific authorization resource linked to a given consent.
      operationId: consentAuthorizationIdGet
      parameters:
        - name: authorizationId
          in: path
          description: Authorization Id
          required: true
          schema:
            type: string
        - name: consentId
          in: path
          description: Consent Id
          required: true
          schema:
            type: string
        - name: orgId
          in: header
          description: JWT header containing tenant-related information
          schema:
            type: string
            default: DEFAULT_ORG
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ConsentResourceResponseBody"
        '404':
          description: Invalid consent id
    put:
      tags:
        - Authorization Resource
      summary: Update Consent Authorization Resource
      description: Update the details of a specific authorization resource associated with the given consent.

      operationId: consentAuthorizationIdPut
      parameters:
        - name: authorizationId
          in: path
          description: Authorization Id
          required: true
          schema:
            type: string
        - name: consentId
          in: path
          description: Consent Id
          required: true
          schema:
            type: string
        - name: orgId
          in: header
          description: JWT header containing tenant-related information
          schema:
            type: string
            default: DEFAULT_ORG
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/AuthorizationResourceRequestBody"
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Invalid consent id
    delete:
      tags:
        - Authorization Resource
      summary: Delete Consent Authorization Resource
      description: Delete a specific authorization resource associated with a given consent.
      operationId: consentAuthorizationIdDelete
      parameters:
        - name: authorizationId
          in: path
          description: Authorization Id
          required: true
          schema:
            type: string
        - name: consentId
          in: path
          description: Consent Id
          required: true
          schema:
            type: string
        - name: orgId
          in: header
          description: JWT header containing tenant-related information
          schema:
            type: string
            default: DEFAULT_ORG
      responses:
        '204':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Invalid consent id, or authorization resource id
  "/consents/{consentId}/authorization-resources":
    get:
      tags:
        - Authorization Resource
      summary: Retrieve Consent Authorization Resources
      description: Retrieve all authorization resources associated with a specific consent.
      operationId: consentAuthorizationGet
      parameters:
        - name: consentId
          in: path
          description: Consent id
          required: true
          schema:
            type: string
        - name: orgId
          in: header
          description: JWT header containing tenant-related information
          schema:
            type: string
            default: DEFAULT_ORG
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Invalid consent id
  "/consents/{consentId}/authorization-resource":
    post:
      tags:
        - Authorization Resource
      summary: Add Consent Authorization Resource
      description: Create new authorization resources and link them to the specified consent.
      operationId: consentAuthorizationIdPost
      parameters:
        - name: consentId
          in: path
          description: Consent id
          required: true
          schema:
            type: string
        - name: orgId
          in: header
          description: JWT header containing tenant-related information
          schema:
            type: string
            default: DEFAULT_ORG
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                "$ref": "#/components/schemas/AuthorizationResourceRequestBody"
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Invalid consent id

  "/consents/{consentId}":
    get:
      tags:
        - Consent Resource
      summary: Consent Retrieval
      description: Retrieve the details of a specific consent using its ID.
      operationId: consentConsentIdGet
      parameters:
        - name: consentId
          in: path
          description: Consent id
          required: true
          schema:
            type: string
        - name: orgId
          in: header
          description: JWT header containing tenant-related information
          schema:
            type: string
            default: DEFAULT_ORG
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ConsentResourceResponseBody"
        '404':
          description: Invalid consent id
    delete:
      tags:
        - Consent Resource
      summary: Consent Purging
      description: Permanently delete the consent and its associated records from the system.
      operationId: consentConsentIdDelete
      parameters:
        - name: consentId
          in: path
          description: Consent id
          required: true
          schema:
            type: string
        - name: orgId
          in: header
          description: JWT header containing tenant-related information
          schema:
            type: string
            default: DEFAULT_ORG
      responses:
        '204':
          description: Successful operation
        '404':
          description: Invalid consent id
  "/consents/{consentId}/expiry-time":
    put:
      tags:
        - Consent Resource
      summary: Consent Expiry Time Update (Seconds)
      description: Update the expiry time of the specified consent in seconds.
      operationId: consentConsentIdExpiryTimePut
      parameters:
        - name: consentId
          in: path
          description: Consent id
          required: true
          schema:
            type: string
        - name: orgId
          in: header
          description: JWT header containing tenant-related information
          schema:
            type: string
            default: DEFAULT_ORG
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/ConsentExpiryTimeUpdateRequestBody"
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid consent id

  "/consents/{consentId}/status":
    put:
      tags:
        - Consent Resource
      summary: Consent Status Update
      operationId: consentConsentIdStatusPut
      description: Update the status (e.g., ACTIVE, REVOKED) of the specified consent.
      parameters:
        - name: consentId
          in: path
          description: Consent id
          required: true
          schema:
            type: string
        - name: orgId
          in: header
          description: JWT header containing tenant-related information
          schema:
            type: string
            default: DEFAULT_ORG
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/ConsentStatusUpdateRequestBody"
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid consent id
  "/consents":
    get:
      tags:
        - Consent Resource
      summary: Consent Search
      description: Search for consents using filters such as type, status, client ID, user ID, and time range.
      operationId: consentGet
      parameters:
        - name: orgId
          in: header
          description: JWT header containing tenant-related information
          schema:
            type: string
            default: DEFAULT_ORG
        - name: consentTypes
          in: query
          schema:
            type: string
        - name: consentStatuses
          in: query
          schema:
            type: string
        - name: clientIds
          in: query
          schema:
            type: string
        - name: userIds
          in: query
          schema:
            type: string
        - name: fromTime
          in: query
          schema:
            type: integer
            format: int32
        - name: toTime
          in: query
          schema:
            type: integer
            format: int32
        - name: limit
          in: query
          schema:
            type: integer
            format: int32
        - name: offset
          in: query
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ConsentResourceResponseBody"
        '400':
          description: Invalid consent id
    post:
      tags:
        - Consent Resource
      summary: Consent Initiation
      description: |
        Creates ConsentResource, AuthorizationResource and ConsentAttributes Entity in the database.

      operationId: consentPost
      parameters:
        - name: orgId
          in: header
          description: JWT header containing tenant-related information
          schema:
            type: string
            default: DEFAULT_ORG
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/ConsentResourceRequestBody"
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ConsentResourceResponseBody"
        '400':
          description: Invalid request body
  "/consents/{consentId}/revoke":
    post:
      tags:
        - Consent Resource
      summary: Consent Revoke
      operationId: consentRevokeConsentIdPost
      description: Revoke a previously granted consent using its ID.
      parameters:
        - name: consentId
          in: path
          description: Consent id
          required: true
          schema:
            type: string
        - name: orgId
          in: header
          description: JWT header containing tenant-related information
          schema:
            type: string
            default: DEFAULT_ORG
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/ConsentRevokeRequestBody"
        required: true
      responses:
        '204':
          description: Successful operation
        '404':
          description: Invalid consent id
  "/consents/status":
    put:
      tags:
        - Consent Resource
      summary: Bulk Consent Status Change
      operationId: consentStatusPut
      description: Perform a bulk update to change the status of multiple consents.
      parameters:
        - name: orgId
          in: header
          description: JWT header containing tenant-related information
          schema:
            type: string
            default: DEFAULT_ORG
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/BulkConsentStatusUpdateResourceRequestBody"
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid consent id
components:
  schemas:
    AuthorizationResourceResponseBody:
      required:
        - authorizationId
        - authorizationStatus
        - authorizationType
        - userId
      type: object
      properties:
        authorizationId:
          type: string
        authorizationStatus:
          type: string
        authorizationType:
          type: string
        userId:
          type: string
        resource:
          type: object
    ConsentResourceResponseBody:
      required:
        - clientId
        - consentId
        - consentType
        - currentStatus
        - expiryTime
        - receipt
        - recurringIndicator
      type: object
      properties:
        consentId:
          type: string
        clientId:
          type: string
          minLength: 1
        consentType:
          type: string
          minLength: 1
        currentStatus:
          type: string
          minLength: 1
        receipt:
          type: object
          minLength: 1
        expiryTime:
          type: integer
          format: int32
        recurringIndicator:
          type: boolean
        consentAttributes:
          type: object
        authorizationResources:
          type: array
          items:
            "$ref": "#/components/schemas/AuthorizationResourceResponseBody"
        createdTime:
          type: integer
          format: int32
        updatedTime:
          type: integer
          format: int32
    AuthorizationResourceRequestBody:
      required:
        - authorizationStatus
        - authorizationType
        - userId
      type: object
      properties:
        authorizationStatus:
          type: string
        authorizationType:
          type: string
        userId:
          type: string
        resource:
          type: object
    ConsentExpiryTimeUpdateRequestBody:
      required:
        - expiryTime
      type: object
      properties:
        expiryTime:
          type: integer
          format: int64
    ConsentHistoryResponse:
      type: object
      properties:
        detailedConsent:
          "$ref": "#/components/schemas/ConsentResourceResponseBody"
        historyId:
          type: string
        consentId:
          type: string
        timestamp:
          type: integer
          format: int32
        reason:
          type: string
    ConsentStatusUpdateRequestBody:
      required:
        - status
        - reason
        - userId
      type: object
      properties:
        status:
          type: string
        reason:
          type: string
        userId:
          type: string
    ConsentResourceRequestBody:
      required:
        - clientId
        - consentType
        - currentStatus
        - expiryTime
        - receipt
      type: object
      properties:
        clientId:
          type: string
        consentType:
          type: string
        currentStatus:
          type: string
          minLength: 3
        receipt:
          type: string
        expiryTime:
          type: integer
          format: int32
        recurringIndicator:
          type: boolean
        consentAttributes:
          type: object
        authorizationResources:
          type: array
          items:
            "$ref": "#/components/schemas/AuthorizationResourceRequestBody"
    ConsentRevokeRequestBody:
      type: object
      properties:
        reason:
          type: string
        userId:
          type: string
    BulkConsentStatusUpdateResourceRequestBody:
      type: object
      properties:
        clientId:
          type: string
        consentType:
          type: string
        applicableStatusesForStateChange:
          type: array
          items:
            type: string
        status:
          type: string
        reason:
          type: string
        userId:
          type: string
